### ISSUE TITLE
Wrong description for the return value in the function tile_encode

### ISSUE THREAD

**Issue by lucolivi** [udacity/reinforcement-learning#1]
The function `tile_encode` (in the notebook **Tile_Coding.ipynb**) has the following description for the return value:

```
Returns
    -------
    encoded_sample : list or array_like
        A list of binary vectors, one for each tiling, or flattened into one.
    """
```

However, the true expected return is a list of **indice vectors** in order to work the later functions and even according to the solution notebook.

**Comment by tomtung** [comment]
Just got really confused by this one too.

**Comment by abhiojha8** [comment]
Updated the return function description in both notebooks.
